[package]
name = "screenshot-scaledown"
version = "0.1.0"
authors = ["Auyer <rafael@rcpassos.me>"]

[dependencies]
scrap = "0.5.0"
repng = "0.2.2"
image = "0.23.4"


[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.8"
features = ["winuser", "synchapi", "consoleapi"]